"""Simple chat function for DeepSeek API."""

import os
from typing import Optional
from .deepseek_client import DeepSeekClient


def simple_chat(prompt: str, api_key: Optional[str] = None, model: str = "deepseek-coder") -> str:
    """Send a prompt to DeepSeek API and return the response.
    
    This function is configured for code generation tasks using the DeepSeek API.
    
    Args:
        prompt: The input prompt/question to send to the API
        api_key: Optional API key. If not provided, will look for DEEPSEEK_API_KEY env variable
        model: The model to use (default: "deepseek-coder" for code generation)
    
    Returns:
        str: The response text generated by the DeepSeek API
    
    Raises:
        ValueError: If no API key is provided or found in environment
        Exception: If the API request fails
    
    Example:
        >>> response = simple_chat("Write a Python function to calculate factorial")
        >>> print(response)
    """
    if api_key is None:
        api_key = os.environ.get("DEEPSEEK_API_KEY")
    
    if not api_key:
        raise ValueError(
            "API key is required. Provide it as an argument or set DEEPSEEK_API_KEY environment variable."
        )
    
    if not prompt or not isinstance(prompt, str):
        raise ValueError("Prompt must be a non-empty string")
    
    client = DeepSeekClient(api_key=api_key)
    
    # Configure for code generation
    system_message = (
        "You are an expert programming assistant. "
        "Provide clear, efficient, and well-documented code solutions. "
        "Include explanations when helpful."
    )
    
    response = client.chat(
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": prompt}
        ],
        model=model,
        temperature=0.7,
        max_tokens=2048
    )
    
    return response
